import type { DimMathQuestion } from "@/types/dim-math";

export const NATURAL_EDEDLER_TEST_A: DimMathQuestion[] = [
  {
    id: "ch1-test-a-q1",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 1,
    questionText:
      "Aşağıdakı təkliflərdən hansıları doğru deyil?\n1) İki natural ədədin cəmi natural ədəddir.\n2) İki natural ədədin fərqi natural ədəddir.\n3) İki natural ədədin nisbəti natural ədəddir.\n4) İki natural ədədin hasili natural ədəddir.",
    choices: [
      { label: "A", text: "1, 4" },
      { label: "B", text: "2, 3" },
      { label: "C", text: "3, 4" },
      { label: "D", text: "1, 2" },
      { label: "E", text: "1, 3" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch1-test-a-q2",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 2,
    questionText:
      "Rəqəmləri fərqli olan üçrəqəmli ədədlərin ən böyüyü ilə ən kiçiyinin cəmini tapın.",
    choices: [
      { label: "A", text: "987" },
      { label: "B", text: "436" },
      { label: "C", text: "1040" },
      { label: "D", text: "1259" },
      { label: "E", text: "1089" },
    ],
    correctAnswer: "E",
  },
  {
    id: "ch1-test-a-q3",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 3,
    questionText: "132506 ədədində neçə on minlik var?",
    choices: [
      { label: "A", text: "32" },
      { label: "B", text: "32506" },
      { label: "C", text: "13" },
      { label: "D", text: "132" },
      { label: "E", text: "3" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch1-test-a-q4",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 4,
    questionText: "23654 ədədində neçə onluq var?",
    choices: [
      { label: "A", text: "54" },
      { label: "B", text: "5" },
      { label: "C", text: "236" },
      { label: "D", text: "2365" },
      { label: "E", text: "23" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q5",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 5,
    questionText:
      "ab ikirəqəmli ədəd olmaqla, ab = a + 8b olarsa, a + b cəmini tapın.",
    choices: [
      { label: "A", text: "9" },
      { label: "B", text: "7" },
      { label: "C", text: "16" },
      { label: "D", text: "63" },
      { label: "E", text: "17" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch1-test-a-q6",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 6,
    questionText:
      "abc üçrəqəmli ədəd olmaqla, abc = 99a + 9b + 9 olarsa, a + b + c cəmini tapın.",
    choices: [
      { label: "A", text: "11" },
      { label: "B", text: "10" },
      { label: "C", text: "9" },
      { label: "D", text: "7" },
      { label: "E", text: "5" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch1-test-a-q7",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 7,
    questionText:
      "a, b və c natural ədədləri üçün ab = 9 və bc = 14 olarsa, a + b + c cəmini tapın.",
    choices: [
      { label: "A", text: "23" },
      { label: "B", text: "28" },
      { label: "C", text: "24" },
      { label: "D", text: "25" },
      { label: "E", text: "19" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch1-test-a-q8",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 8,
    questionText:
      "Aşağıdakılardan hansı n-in bütün natural qiymətlərində təkdir?",
    choices: [
      { label: "A", text: "n² + 2n" },
      { label: "B", text: "n² + 5n" },
      { label: "C", text: "n(n + 3)" },
      { label: "D", text: "4n² + 4n + 1" },
      { label: "E", text: "n² + n + 6" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q9",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 9,
    questionText:
      "Aşağıdakılardan hansı n-in bütün natural qiymətlərində cütdür?",
    choices: [
      { label: "A", text: "n² − n + 1" },
      { label: "B", text: "n(n + 1)(n + 2) + 3" },
      { label: "C", text: "(n + 1)(n + 2)" },
      { label: "D", text: "n(n + 2)(n + 4)" },
      { label: "E", text: "n² + 2n" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch1-test-a-q10",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 10,
    questionText:
      "n cüt natural ədəd olarsa, aşağıdakılardan hansı həmişə cüt natural ədəddir?",
    choices: [
      { label: "A", text: "n + 1" },
      { label: "B", text: "2n + 1" },
      { label: "C", text: "3n + 5" },
      { label: "D", text: "n² + 2" },
      { label: "E", text: "7n + 1" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q11",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 11,
    questionText:
      "a tək natural ədəd olarsa, aşağıdakılardan hansı həmişə cüt natural ədəddir?",
    choices: [
      { label: "A", text: "a³ + a² + 1" },
      { label: "B", text: "a⁶ + a⁴ + 3" },
      { label: "C", text: "a + 2" },
      { label: "D", text: "a⁴ + a²" },
      { label: "E", text: "a² + 10" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q12",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 12,
    questionText:
      "Üç ardıcıl tək natural ədədin cəmi 99-a bərabər olarsa, bu ədədlərin böyüyünü tapın.",
    choices: [
      { label: "A", text: "47" },
      { label: "B", text: "35" },
      { label: "C", text: "31" },
      { label: "D", text: "37" },
      { label: "E", text: "41" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch1-test-a-q13",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 13,
    questionText:
      "Üç ardıcıl cüt natural ədədin cəmi 372 olarsa, ən kiçik ədədi tapın.",
    choices: [
      { label: "A", text: "124" },
      { label: "B", text: "122" },
      { label: "C", text: "120" },
      { label: "D", text: "126" },
      { label: "E", text: "128" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch1-test-a-q14",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 14,
    questionText:
      "Bölən 11, natamam qismət 9 və qalıq 4 olarsa, bölünəni tapın.",
    choices: [
      { label: "A", text: "103" },
      { label: "B", text: "102" },
      { label: "C", text: "53" },
      { label: "D", text: "99" },
      { label: "E", text: "44" },
    ],
    correctAnswer: "A",
  },
  {
    id: "ch1-test-a-q15",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 15,
    questionText: "Bölən 9, qismət 13 və qalıq 8 olarsa, bölünəni tapın.",
    choices: [
      { label: "A", text: "96" },
      { label: "B", text: "97" },
      { label: "C", text: "125" },
      { label: "D", text: "102" },
      { label: "E", text: "103" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch1-test-a-q16",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 16,
    questionText:
      "10234x ədədi 3-ə tam bölünür. x-in ala biləcəyi qiymətlərin cəmini tapın.",
    choices: [
      { label: "A", text: "12" },
      { label: "B", text: "13" },
      { label: "C", text: "14" },
      { label: "D", text: "15" },
      { label: "E", text: "16" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q17",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 17,
    questionText:
      "243a6 ədədi 4-ə tam bölünür. a-nın ala biləcəyi qiymətlərin cəmini tapın.",
    choices: [
      { label: "A", text: "16" },
      { label: "B", text: "18" },
      { label: "C", text: "21" },
      { label: "D", text: "25" },
      { label: "E", text: "27" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q18",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 18,
    questionText: "Aşağıdakı ədədlərdən hansı 6-ya tam bölünür?",
    choices: [
      { label: "A", text: "2047" },
      { label: "B", text: "1234" },
      { label: "C", text: "3458" },
      { label: "D", text: "4035" },
      { label: "E", text: "5004" },
    ],
    correctAnswer: "E",
  },
  {
    id: "ch1-test-a-q19",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 19,
    questionText:
      "Aşağıdakı ədədlərdən hansı həm 4-ə, həm də 9-a tam bölünür?",
    choices: [
      { label: "A", text: "24564" },
      { label: "B", text: "28004" },
      { label: "C", text: "37219" },
      { label: "D", text: "256716" },
      { label: "E", text: "287217" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch1-test-a-q20",
    chapterId: 1,
    testName: "TEST A",
    questionType: "multiple-choice",
    questionNumber: 20,
    questionText:
      "2345 · 3687 hasilinin 5-ə bölünməsindən alınan qalığı tapın.",
    choices: [
      { label: "A", text: "2" },
      { label: "B", text: "1" },
      { label: "C", text: "0" },
      { label: "D", text: "3" },
      { label: "E", text: "4" },
    ],
    correctAnswer: "C",
  },
];
