import type { DimMathQuestion } from "@/types/dim-math";

const SITUASIYA_TEXT =
  "Düzgün çoxbucaqlının bir daxili bucağının dərəcə ölçüsü $360$-ın bölünəni olarsa, bu çoxbucaqlılarla sahəni boşluq qalmadan örtmək (parketləmək) mümkündür.";

export const SINAQ_10_QEBUL: DimMathQuestion[] = [
  {
    id: "ch37-sinaq10-q1",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 1,
    questionType: "multiple-choice",
    questionText:
      "$\\frac{k}{A}$ düzgün kəsri $k$-nın hər bir natural qiymətində sonsuz dövrü onluq kəsr olarsa, $A$ aşağıdakılardan hansı ola bilər?",
    choices: [
      { label: "A", text: "$10$" },
      { label: "B", text: "$12$" },
      { label: "C", text: "$16$" },
      { label: "D", text: "$18$" },
      { label: "E", text: "$21$" },
    ],
    correctAnswer: "E",
  },
  {
    id: "ch37-sinaq10-q2",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 2,
    questionType: "multiple-choice",
    questionText:
      "Düzgün çoxbucaqlının bir təpədən çıxan iki ən kiçik diaqonalı arasında qalan bucaq $140^\\circ$ olarsa, bu çoxbucaqlının tərəflərinin sayını tapın.",
    choices: [
      { label: "A", text: "$20$" },
      { label: "B", text: "$18$" },
      { label: "C", text: "$15$" },
      { label: "D", text: "$12$" },
      { label: "E", text: "$10$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q3",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 3,
    questionType: "multiple-choice",
    questionText:
      "$\\int_0^{\\frac{\\pi}{3}} \\frac{1}{\\cos^2 x}\\,dx$ inteqralını hesablayın.",
    choices: [
      { label: "A", text: "$\\sqrt{3}$" },
      { label: "B", text: "$1$" },
      { label: "C", text: "$\\frac{\\sqrt{2}}{2}$" },
      { label: "D", text: "$\\frac{\\sqrt{3}}{3}$" },
      { label: "E", text: "$\\frac{1}{2}$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q4",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 4,
    questionType: "multiple-choice",
    questionText:
      "$y = \\frac{x-3}{x-6}$ funksiyasının təyin oblastını tapın.",
    choices: [
      { label: "A", text: "$(-\\infty;\\,0)\\cup(0;\\,+\\infty)$" },
      { label: "B", text: "$(-\\infty;\\,3)\\cup(3;\\,+\\infty)$" },
      { label: "C", text: "$(-\\infty;\\,2)\\cup(2;\\,+\\infty)$" },
      { label: "D", text: "$(-\\infty;\\,6)\\cup(6;\\,+\\infty)$" },
      { label: "E", text: "$(-\\infty;\\,4)\\cup(4;\\,+\\infty)$" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch37-sinaq10-q5",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 5,
    questionType: "multiple-choice",
    questionText:
      "$A$, $B$, $C$ və $D$ nöqtələri düz xətt üzərində ardıcıl qeyd olunmuşdur. $AC = a$, $BD = b$ və $AD = c$ olarsa, $BC$ parçasını $a$, $b$ və $c$ ilə ifadə edin.",
    choices: [
      { label: "A", text: "$c - a - b$" },
      { label: "B", text: "$a + b - c$" },
      { label: "C", text: "$2c - a - b$" },
      { label: "D", text: "$2a + 2b - c$" },
      { label: "E", text: "$a + b - 0{,}5c$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q6",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 6,
    questionType: "multiple-choice",
    questionText: "$4(x+1) \\geq x + 19$ bərabərsizliyini həll edin.",
    choices: [
      { label: "A", text: "$x \\geq 6$" },
      { label: "B", text: "$x \\geq 5$" },
      { label: "C", text: "$x \\geq 4$" },
      { label: "D", text: "$x \\geq 3$" },
      { label: "E", text: "$x \\geq 2$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q7",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 7,
    questionType: "multiple-choice",
    questionText:
      "$\\triangle ABC$-də $AH$ hündürlüyü, $BT$ tənböləni və $CM$ medianı çəkilmişdir. $AH = BT = CM$ olarsa, aşağıdakılardan hansı doğrudur?",
    choices: [
      { label: "A", text: "$AB < AC < BC$" },
      { label: "B", text: "$AB < BC < AC$" },
      { label: "C", text: "$BC < AC < AB$" },
      { label: "D", text: "$BC < AB < AC$" },
      { label: "E", text: "$AC < BC < AB$" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch37-sinaq10-q8",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 8,
    questionType: "multiple-choice",
    questionText:
      "$z = i - 1$ kompleks ədədinin əksi ilə qoşmasının hasilini tapın.",
    choices: [
      { label: "A", text: "$-2$" },
      { label: "B", text: "$-1$" },
      { label: "C", text: "$0$" },
      { label: "D", text: "$1$" },
      { label: "E", text: "$2$" },
    ],
    correctAnswer: "A",
  },
  {
    id: "ch37-sinaq10-q9",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 9,
    questionType: "multiple-choice",
    questionText:
      "$k$ tam ədəddir, $\\frac{x^2 + k}{x + 3}$ rasional ifadəsini ixtisar etdikdə $ax - b$ ikihədlisi alınırsa, $k(a+b)$ hasilini tapın.",
    choices: [
      { label: "A", text: "$0$" },
      { label: "B", text: "$-9$" },
      { label: "C", text: "$18$" },
      { label: "D", text: "$-27$" },
      { label: "E", text: "$36$" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch37-sinaq10-q10",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 10,
    questionType: "multiple-choice",
    questionText:
      "$\\lim_{x \\to 3} \\frac{x^2 - 9}{x^2 - 7x + 12}$-i hesablayın.",
    choices: [
      { label: "A", text: "$-6$" },
      { label: "B", text: "$-3$" },
      { label: "C", text: "$2$" },
      { label: "D", text: "$4$" },
      { label: "E", text: "$8$" },
    ],
    correctAnswer: "A",
  },
  {
    id: "ch37-sinaq10-q11",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 11,
    questionType: "multiple-choice",
    diagramId: "sinaq-10-q11",
    questionText:
      "$A$, $B$ və $C$ nöqtələri çevrə üzərindədir. $\\cup ABC = 260^\\circ$ olarsa, $\\angle ABC$-ni tapın.",
    choices: [
      { label: "A", text: "$78^\\circ$" },
      { label: "B", text: "$65^\\circ$" },
      { label: "C", text: "$55^\\circ$" },
      { label: "D", text: "$50^\\circ$" },
      { label: "E", text: "$52^\\circ$" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch37-sinaq10-q12",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 12,
    questionType: "multiple-choice",
    questionText:
      "$|\\cos x| = 1$ tənliyinin $[0;\\,2\\pi)$ intervalındakı köklərinin sayını tapın.",
    choices: [
      { label: "A", text: "$1$" },
      { label: "B", text: "$2$" },
      { label: "C", text: "$3$" },
      { label: "D", text: "$4$" },
      { label: "E", text: "$5$" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch37-sinaq10-q13",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 13,
    questionType: "multiple-choice",
    questionText:
      "Tərəfləri $a$ sm və $b$ sm, sahəsi isə $S$ sm$^2$ olan düzbucaqlının sahəsi (sm$^2$-lə) tərəflərinin (sm-lə) həndəsi ortasına bərabər olarsa, sahəsini tapın.",
    choices: [
      { label: "A", text: "$4$ sm$^2$" },
      { label: "B", text: "$2$ sm$^2$" },
      { label: "C", text: "$\\sqrt{3}$ sm$^2$" },
      { label: "D", text: "$\\sqrt{2}$ sm$^2$" },
      { label: "E", text: "$1$ sm$^2$" },
    ],
    correctAnswer: "E",
  },
  {
    id: "ch37-sinaq10-q14",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 14,
    questionType: "multiple-choice",
    questionText:
      "$y = 2x^2 - 8x + 16$ parabolasına hansı nöqtədə çəkilmiş toxunan absis oxuna paraleldir?",
    choices: [
      { label: "A", text: "$0$" },
      { label: "B", text: "$2$" },
      { label: "C", text: "$4$" },
      { label: "D", text: "$8$" },
      { label: "E", text: "$16$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q15",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 15,
    questionType: "multiple-choice",
    questionText: "$-2\\sqrt{5}$ ifadəsində vuruğu kök işarəsi altına salın.",
    choices: [
      { label: "A", text: "$-\\sqrt{-10}$" },
      { label: "B", text: "$-\\sqrt{-20}$" },
      { label: "C", text: "$\\sqrt{-50}$" },
      { label: "D", text: "$-\\sqrt{20}$" },
      { label: "E", text: "$\\sqrt{-10}$" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch37-sinaq10-q16",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 16,
    questionType: "multiple-choice",
    questionText:
      "$$\\begin{cases} ax - y = -c \\\\ 4x + by = 6 \\end{cases}$$ tənliklər sisteminin sonsuz sayda həlli var və koordinat sistemində bu həllər çoxluğu $y = 2x - 3$ düz xəttini əmələ gətirirsə, $abc$ hasilini tapın.",
    choices: [
      { label: "A", text: "$-8$" },
      { label: "B", text: "$12$" },
      { label: "C", text: "$-16$" },
      { label: "D", text: "$18$" },
      { label: "E", text: "$-24$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q17",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 17,
    questionType: "multiple-choice",
    questionText:
      "Sinfin 60%-i qız şagirdləridir və həmin qızların 20%-i eynəklidir. Sinifdən təsadüfən seçilən bir şagirdin eynəkli qız olması ehtimalını tapın.",
    choices: [
      { label: "A", text: "$\\frac{1}{40}$" },
      { label: "B", text: "$\\frac{1}{20}$" },
      { label: "C", text: "$\\frac{2}{25}$" },
      { label: "D", text: "$\\frac{3}{20}$" },
      { label: "E", text: "$\\frac{3}{25}$" },
    ],
    correctAnswer: "E",
  },
  {
    id: "ch37-sinaq10-q18",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 18,
    questionType: "multiple-choice",
    questionText:
      "Başlanğıc nöqtəsi $A(-4;\\,-3)$ və son nöqtəsi $B(-2;\\,-1)$ olan $\\vec{AB}$ vektorunun meyl bucağını tapın.",
    choices: [
      { label: "A", text: "$30^\\circ$" },
      { label: "B", text: "$45^\\circ$" },
      { label: "C", text: "$60^\\circ$" },
      { label: "D", text: "$90^\\circ$" },
      { label: "E", text: "$120^\\circ$" },
    ],
    correctAnswer: "B",
  },
  {
    id: "ch37-sinaq10-q19",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 19,
    questionType: "multiple-choice",
    diagramId: "sinaq-10-q19",
    questionText:
      "$ABC$ bərabərtərəfli üçbucaq, $G$ ağırlıq mərkəzi, $DE \\parallel AC$ və $P_{\\triangle ABC} = 360$ sm olarsa, $DE$-ni tapın.",
    choices: [
      { label: "A", text: "$100$ sm" },
      { label: "B", text: "$96$ sm" },
      { label: "C", text: "$90$ sm" },
      { label: "D", text: "$80$ sm" },
      { label: "E", text: "$60$ sm" },
    ],
    correctAnswer: "D",
  },
  {
    id: "ch37-sinaq10-q20",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 20,
    questionType: "multiple-choice",
    questionText:
      "Tam səthinin sahəsi $36\\pi$ sm$^2$ olan kürənin həcmini tapın.",
    choices: [
      { label: "A", text: "$18\\pi$ sm$^3$" },
      { label: "B", text: "$27\\pi$ sm$^3$" },
      { label: "C", text: "$36\\pi$ sm$^3$" },
      { label: "D", text: "$54\\pi$ sm$^3$" },
      { label: "E", text: "$72\\pi$ sm$^3$" },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch37-sinaq10-q21",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 21,
    questionType: "multiple-choice",
    questionText:
      "$y = 2^{x-5} - 1$ funksiyası üçün aşağıdakılardan hansı doğru deyil?",
    choices: [
      {
        label: "A",
        text: "Təyin oblastı $(-\\infty;\\,+\\infty)$ çoxluğudur.",
      },
      {
        label: "B",
        text: "Qiymətlər çoxluğuna daxil olan ən kiçik tam ədəd 0-dır.",
      },
      {
        label: "C",
        text: "$(-\\infty;\\,0)$ intervalında artandır.",
      },
      {
        label: "D",
        text: "$Ox$ oxunu $(5;\\,0)$ nöqtəsində kəsir.",
      },
      { label: "E", text: "Dövrü deyil." },
    ],
    correctAnswer: "C",
  },
  {
    id: "ch37-sinaq10-q22",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 22,
    questionType: "multiple-choice",
    questionText:
      "$ABCD$ düzbucaqlısında $AB = 15$ sm və $BC = 20$ sm olarsa, $D$ təpəsindən $BC$ diaqonalına qədər məsafəni tapın.",
    choices: [
      { label: "A", text: "$5$ sm" },
      { label: "B", text: "$8$ sm" },
      { label: "C", text: "$9$ sm" },
      { label: "D", text: "$10$ sm" },
      { label: "E", text: "$12$ sm" },
    ],
    correctAnswer: "E",
  },
  {
    id: "ch37-sinaq10-q23",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 23,
    questionType: "open",
    questionText:
      "$n(A \\setminus B) = n(A \\cap B) = n(B \\setminus A) = 6$ olarsa, $n(A \\cup B)$-ni tapın.",
    correctAnswer: "18",
    acceptedAnswers: ["18"],
  },
  {
    id: "ch37-sinaq10-q24",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 24,
    questionType: "open",
    questionText:
      "68 kq, 102 kq və 170 kq ağırlığında üç kisə düyü bir-birinə qarışdırılmadan bərabər tutumlu qablara doldurulmalıdır. Bunun üçün artıq düyünün qalmaması şərtilə ən azı neçə qab lazımdır?",
    correctAnswer: "10",
    acceptedAnswers: ["10"],
  },
  {
    id: "ch37-sinaq10-q25",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 25,
    questionType: "open",
    questionText:
      "Bakı və Şəki arasındakı məsafə 300 km-dir. Miqyası 1 : 6000000 olan xəritədə bu məsafə neçə sm olar?",
    correctAnswer: "5",
    acceptedAnswers: ["5", "5 sm", "5cm"],
  },
  {
    id: "ch37-sinaq10-q26",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 26,
    questionType: "open",
    questionText:
      "Hansı müsbət ədədin tam hissəsi kəsr hissəsindən 2 dəfə böyükdür?",
    correctAnswer: "1.5",
    acceptedAnswers: ["1.5", "1,5", "3/2"],
  },
  {
    id: "ch37-sinaq10-q27",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 27,
    questionType: "open",
    questionText:
      "$x^2 + 4x + 1 = 0$ tənliyinin kökləri $x_1$ və $x_2$ olarsa, uyğunluğu müəyyən edin.\n1. $x_1^2 + x_2^2$\n2. $x_1^3 + x_2^3$\n3. $\\frac{1}{x_1} + \\frac{1}{x_2}$\na. $-76$\nb. $-52$\nc. $14$\nd. $-4$\ne. $6$",
    correctAnswer: "1B2C3D",
    acceptedAnswers: ["1b2c3d", "1B2C3D", "1 B 2 C 3 D"],
  },
  {
    id: "ch37-sinaq10-q28",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 28,
    questionType: "open",
    questionText: `${SITUASIYA_TEXT}\n\n$n$-in neçə qiymətində düzgün $n$-bucaqlının bir daxili bucağının dərəcə ölçüsü $360$-ın bölünənidir?`,
    correctAnswer: "3",
    acceptedAnswers: ["3"],
  },
  {
    id: "ch37-sinaq10-q29",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 29,
    questionType: "open",
    questionText: `${SITUASIYA_TEXT}\n\nEni 3,5 m və uzunluğu 6 m olan düzbucaqlı formasında sahəni parketləmək üçün tərəfi 10 sm olan neçə kvadrat şəkilli parket lazımdır?`,
    correctAnswer: "2100",
    acceptedAnswers: ["2100"],
  },
  {
    id: "ch37-sinaq10-q30",
    chapterId: 37,
    testName: "Sınaq 10 - Qəbul",
    questionNumber: 30,
    questionType: "open",
    questionText: `${SITUASIYA_TEXT}\n\nDüzgün 6-bucaqlı parketin tərəfi sahəsi $36\\sqrt{3}$ sm$^2$ olan düzgün 3-bucaqlı parketin tərəfindən 2 dəfə kiçikdir. Bu 6-bucaqlı parketin sahəsini tapın.`,
    correctAnswer: "54√3",
    acceptedAnswers: [
      "54√3",
      "54*√3",
      "54sqrt3",
      "54√3 sm²",
      "54\\sqrt{3}",
    ],
  },
];
